### ISSUE TITLE
To Do Checklist

### ISSUE THREAD

**Issue by phegde19** [UTDallasEPICS/Wellness-Center-Older-Adults#86]
# Task List
### Login Page
- [x] Sign in with Auth0
- [ ] Update login page UI
## Home Page
 - [x] Dashboard button
 - [ ] Log Out button
## Admin Features
- Dashboard
  - [ ] Fix Dashboard Page UI
  - [x] View total volunteer hours
  - [x] Number of recently completed rides
  - [x] Total rides for the week
- Rides
  - [ ] UI on Rides Page
  - [x] Add new rides, edit, and delete
  - [ ] Digital Pickup Time
  - [x] View available rides
  - [x] View reserved rides
  - [x] View completed rides
- Volunteers
  - [x] Store information about volunteers
  - [ ] Add new volunteers
  - [ ] Edit volunteers
- Clients
  - [x] Store information about clients
  - [x] Add new clients
  - [ ] Edit clients
- Admin
  - [ ]  Manage system configurations and settings.
## Volunteer Features
- Ride Listings
  - [ ] View available rides
  - [ ] Sign up for available rides
  - [ ] Cancel rides
  - [ ] View all reserved rides
- Hours
  - [ ] View total hours
  - [ ] View history
  - Settings
  - [ ] Edit contact details

**Comment by devAgant** [comment]
duplicate
